/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t;

#include <stdint.h>

#define RCC_BASE 	0x40021000
#define GPIOA_BASE 	0x40010800
#define RCC_APB2ENR *(volatile uint32_t*)(RCC_BASE + 0x18)  // BIT 2 =1                 //this enables the GPIO
#define GPIOA_CRH 	*(volatile uint32_t*)(GPIOA_BASE + 0x04) // 20 TO 23 BITS = 0010 (2) //this like control settings
#define GPIOA_ODR 	*(volatile uint32_t*)(GPIOA_BASE + 0x0C) // BIT 13 = 1			   //the bit value it self
/* It essentially tells the compiler that we want to treat the 
calculated memory address as a pointer to a 32-bit unsigned 
integer that can change unpredictably (volatile). */

#define EXTI0_BASE		 0x40010400
#define AFIO_BASE		 0x40010000
#define EXTI0_IMR 		*(volatile uint32_t*)(EXTI0_BASE+0x00)
#define EXTI0_RTSR	 	*(volatile uint32_t*)(EXTI0_BASE+0x08)
#define EXTI0_PR 		*(volatile uint32_t*)(EXTI0_BASE+0x14)
#define AFIO_EXTICR1 	*(volatile uint32_t*)(AFIO_BASE +0x08)

#define RCC_IOPAEN 	(1<<2)
#define GPIOA13		(1UL<<13)

void clock_init(){
	RCC_APB2ENR |= RCC_IOPAEN;
}

void GPIO_init(){
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;
}

int main(void) {
	clock_init();
	GPIO_init();
	
	/* Enable EXTI0_IMS Line 0 (PA0) */
	EXTI0_IMR |= (1<<0);
	
	/* Enable EXTI0_RTSR Line 0 (PA0) */
	EXTI0_RTSR |= (1<<0);

	/* Set the Altrnative function to select EXTI0 (port 0) */
	AFIO_EXTICR1 = 0;


	// read the pin with the enabled interrupt
	
	while(1);

	return 0;
}

void EXTI0_IRQHandler(void){
	//toggle pin
	GPIOA_ODR ^= (1<<13);
	// but first we need to do some steps
	// 1- enable EXTI_IMS
	// 2- set the edge detector
	// 3- pending reg
	
	/* Clear EXTI0_PR Line 0 (PA0) */
	EXTI0_PR |= (1<<0);
}
